# Generated by Django 4.2.30 on 2026-08-07 22:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=120)),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('wavelength', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fluence', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('spot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_types', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='clients.client')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='laser.proceduretype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
