# Generated by Django 4.2.30 on 2026-08-07 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lasersession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lasersession',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='laser.procedure'),
        ),
        migrations.AlterUniqueTogether(
            name='proceduretype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddConstraint(
            model_name='lasersession',
            constraint=models.UniqueConstraint(fields=('procedure', 'number'), name='unique_session_number'),
        ),
    ]
