# Generated by Django 5.2.17 on 2026-08-08 00:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasersession',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='equipment',
            field=models.CharField(blank=True, max_length=120, verbose_name='equipamento'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='fluence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='fluência'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='frequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número da sessão'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='observations',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laser_sessions', to=settings.AUTH_USER_MODEL, verbose_name='operador'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='region',
            field=models.CharField(max_length=120, verbose_name='região'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='spot_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='spot size'),
        ),
        migrations.AlterField(
            model_name='lasersession',
            name='wavelength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='comprimento de onda (nm)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nome'),
        ),
    ]
